language: ruby
rvm:
 - 2.5.3

deploy:
  provider: heroku
  app: lp71-project-henriot
  api_key:
    secure: 6a9b2d06-8698-408b-a443-6c4638b4aa83

services: postgresql

script:
 - bin/rails db:migrate RAILS_ENV=test

before_script:
# - psql -c "create user fabien with password 'pgsql';" -U postgres
 - psql -c 'create database travis_ci_test' -U postgres
 - cp config/database.yml.travis config/database.yml
